--ORACLE DB
--Eliminacion de las tablas
DROP TABLE JORGE.CATEGORY PURGE;
DROP TABLE JORGE.TYPE_PERSON PURGE;
DROP PACKAGE CATEGORY_API;
/
--Creacion de las tablas
create table category (
		id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
		name varchar(50) NOT NULL,
		description varchar(300),
		primary key (id)
	);
/	
create table type_person (
		id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY, -- serial crea una secuencia de manera automatica y no es necesario establecer id
		name varchar(50) NOT NULL,
		description varchar(300),
		primary key (id)
	);
/
--Creacion de los procedimientos almacenados
create or replace PACKAGE category_api AS
	procedure ins (p_NAME in CATEGORY.NAME%type,p_DESCRIPTION in CATEGORY.DESCRIPTION%type default null);
	procedure upd (p_ID IN CATEGORY.ID%TYPE, p_NAME in CATEGORY.NAME%TYPE, p_DESCRIPTION in CATEGORY.DESCRIPTION%type default null);
	procedure del (p_ID in CATEGORY.ID%type);
	PROCEDURE LIST(CATEGORIES_C OUT SYS_REFCURSOR);
    procedure search(p_texto IN varchar2,CATEGORIES_C OUT SYS_REFCURSOR);
    procedure getCategory(p_id IN category.id%TYPE,CATEGORIES_C OUT SYS_REFCURSOR);
END category_api;
/
create or replace NONEDITIONABLE PACKAGE BODY category_api AS
	procedure ins (p_NAME in CATEGORY.NAME%type,p_DESCRIPTION in CATEGORY.DESCRIPTION%type default null) 
	is
	begin
		insert into CATEGORY(DESCRIPTION,NAME) values (p_DESCRIPTION,p_NAME);
		COMMIT;
	end;

	procedure del (p_ID in CATEGORY.ID%type) 
	IS
	BEGIN
		delete from CATEGORY where ID = p_ID;
		COMMIT;
	end;

	procedure upd (p_ID IN CATEGORY.ID%TYPE, p_NAME in CATEGORY.NAME%TYPE, p_DESCRIPTION in CATEGORY.DESCRIPTION%type default null) 
	is
	begin
		update CATEGORY set	DESCRIPTION = p_DESCRIPTION, NAME = p_NAME
		where ID = p_ID;
		COMMIT;
	end;

	PROCEDURE LIST(CATEGORIES_C OUT SYS_REFCURSOR)
	IS
	BEGIN 
		OPEN CATEGORIES_C FOR 
			SELECT * 
			FROM CATEGORY c;
	END LIST;
    
    procedure search(p_texto IN varchar2,CATEGORIES_C OUT SYS_REFCURSOR)
    IS
    BEGIN
        OPEN CATEGORIES_C FOR
            SELECT *
            FROM CATEGORY c
            WHERE UPPER(c.name) ||' '|| upper(c.description) like '%'||upper(p_texto)||'%';
    END;
    
    procedure getCategory(p_id IN category.id%TYPE,CATEGORIES_C OUT SYS_REFCURSOR)
    IS
    BEGIN
        OPEN CATEGORIES_C FOR
            SELECT *
            FROM CATEGORY c
            WHERE c.id = p_id ;
    END;

END category_api;
/
create or replace PACKAGE type_person_api AS
	procedure ins (p_NAME in TYPE_PERSON.NAME%type,p_DESCRIPTION in TYPE_PERSON.DESCRIPTION%type default null);
	procedure upd (p_ID IN TYPE_PERSON.ID%TYPE, p_NAME in TYPE_PERSON.NAME%TYPE, p_DESCRIPTION in TYPE_PERSON.DESCRIPTION%type default null);
	procedure del (p_ID in TYPE_PERSON.ID%type) ;
	procedure list(TYPE_PEOPLE_C OUT SYS_REFCURSOR);
    procedure search(p_texto IN varchar2, TYPE_PEOPLE_C OUT SYS_REFCURSOR);
    procedure getTypePerson(p_id IN category.id%TYPE,TYPE_PERSON_C OUT SYS_REFCURSOR);
END type_person_api;
/
create or replace PACKAGE BODY type_person_api AS
	procedure ins (p_NAME in TYPE_PERSON.NAME%type,p_DESCRIPTION in TYPE_PERSON.DESCRIPTION%type default null) 
	is
	begin
		insert into TYPE_PERSON(DESCRIPTION,NAME) values (p_DESCRIPTION,p_NAME);
		COMMIT;
	end;

	procedure upd (p_ID IN TYPE_PERSON.ID%TYPE, p_NAME in TYPE_PERSON.NAME%TYPE, p_DESCRIPTION in TYPE_PERSON.DESCRIPTION%type default null) 
	is
	begin
		update TYPE_PERSON set DESCRIPTION = p_DESCRIPTION, NAME = p_NAME
		where ID = p_ID;
		COMMIT;
	end;

    procedure del (p_ID in TYPE_PERSON.ID%type) 
	IS
	BEGIN
		delete from TYPE_PERSON where ID = p_ID;
		COMMIT;
	end;

	procedure list(TYPE_PEOPLE_C OUT SYS_REFCURSOR)
	IS
	BEGIN 
		OPEN TYPE_PEOPLE_C FOR 
			SELECT * 
			FROM TYPE_PERSON c;
            
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            dbms_output.put_line('No hay datos de category');
	END LIST;
    
    procedure search(p_texto IN varchar2, TYPE_PEOPLE_C OUT SYS_REFCURSOR)
    IS
    BEGIN
        OPEN TYPE_PEOPLE_C FOR
            SELECT *
            FROM TYPE_PERSON c
            WHERE UPPER(c.name) ||' '|| upper(c.description) like '%'||upper(p_texto)||'%';
    
    END;
    
    procedure getTypePerson(p_id IN category.id%TYPE,TYPE_PERSON_C OUT SYS_REFCURSOR)
    IS
    BEGIN
        OPEN TYPE_PERSON_C FOR
            SELECT *
            FROM TYPE_PERSON c
            WHERE c.id = p_id ;
    END;

END type_person_api;
/